site_name: Kingdom of God
theme:
  name: material
  feature:
    tabs: true
use_directory_urls: false
markdown_extensions:
  - plantuml_markdown
google_analytics: ['UA-163807440-1', 'jazemzer.github.io/kingdom-of-god']

nav:
  - 'Primary': 'primary.md'
  - 'Secondary': 'secondary.md'
  - 'Keys': 'keys.md'
  - 'Parables': 'parables.md'
  - 'Qualifications': 'qualifications.md'
  - 'Checklist': 'checklist.md'
  - 'How to seek': 'seeking.md'
  - 'Tertiary': 'tertiary.md'