site_name: Kingdom of God
theme:
  name: material
  feature:
    tabs: true
use_directory_urls: false
markdown_extensions:
  - plantuml_markdown
google_analytics: ['UA-163807440-3', 'jazemzer.github.io/kingdom']

nav:
  - 'Fundamentals': 'fundamentals.md'
  - 'Properties': 'properties.md'
  - 'Secondary': 'secondary.md'
  - 'Keys': 'keys.md'
  - 'Parables': 'parables.md'
  - 'Qualifications': 'qualifications.md'
  - 'Checklist': 'checklist.md'
  - 'How to seek': 'seeking.md'
  - 'Gospel of the Kingdom' : 'gospel.md'
  - 'Tertiary': 'tertiary.md'